//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaBandaEdoOaxaca.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        SistemaBandaEdoOaxaca.ServiceReference1.HelloWorldResponse HelloWorld(SistemaBandaEdoOaxaca.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.ServiceReference1.HelloWorldResponse> HelloWorldAsync(SistemaBandaEdoOaxaca.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name MarioResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Mario", ReplyAction="*")]
        SistemaBandaEdoOaxaca.ServiceReference1.MarioResponse Mario(SistemaBandaEdoOaxaca.ServiceReference1.MarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Mario", ReplyAction="*")]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.ServiceReference1.MarioResponse> MarioAsync(SistemaBandaEdoOaxaca.ServiceReference1.MarioRequest request);
        
        // CODEGEN: Generating message contract since element name numero from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/THI", ReplyAction="*")]
        SistemaBandaEdoOaxaca.ServiceReference1.THIResponse THI(SistemaBandaEdoOaxaca.ServiceReference1.THIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/THI", ReplyAction="*")]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.ServiceReference1.THIResponse> THIAsync(SistemaBandaEdoOaxaca.ServiceReference1.THIRequest request);
        
        // CODEGEN: Generating message contract since element name numero from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Estacion", ReplyAction="*")]
        SistemaBandaEdoOaxaca.ServiceReference1.EstacionResponse Estacion(SistemaBandaEdoOaxaca.ServiceReference1.EstacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Estacion", ReplyAction="*")]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.ServiceReference1.EstacionResponse> EstacionAsync(SistemaBandaEdoOaxaca.ServiceReference1.EstacionRequest request);
        
        // CODEGEN: Generating message contract since element name numero from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EstacionDatos", ReplyAction="*")]
        SistemaBandaEdoOaxaca.ServiceReference1.EstacionDatosResponse EstacionDatos(SistemaBandaEdoOaxaca.ServiceReference1.EstacionDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EstacionDatos", ReplyAction="*")]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.ServiceReference1.EstacionDatosResponse> EstacionDatosAsync(SistemaBandaEdoOaxaca.ServiceReference1.EstacionDatosRequest request);
        
        // CODEGEN: Generating message contract since element name GetDataStationTemtHumrResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataStationTemtHumr", ReplyAction="*")]
        SistemaBandaEdoOaxaca.ServiceReference1.GetDataStationTemtHumrResponse GetDataStationTemtHumr(SistemaBandaEdoOaxaca.ServiceReference1.GetDataStationTemtHumrRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataStationTemtHumr", ReplyAction="*")]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.ServiceReference1.GetDataStationTemtHumrResponse> GetDataStationTemtHumrAsync(SistemaBandaEdoOaxaca.ServiceReference1.GetDataStationTemtHumrRequest request);
        
        // CODEGEN: Generating message contract since element name GPSEstacionesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GPSEstaciones", ReplyAction="*")]
        SistemaBandaEdoOaxaca.ServiceReference1.GPSEstacionesResponse GPSEstaciones(SistemaBandaEdoOaxaca.ServiceReference1.GPSEstacionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GPSEstaciones", ReplyAction="*")]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.ServiceReference1.GPSEstacionesResponse> GPSEstacionesAsync(SistemaBandaEdoOaxaca.ServiceReference1.GPSEstacionesRequest request);
        
        // CODEGEN: Generating message contract since element name edo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEstaciones", ReplyAction="*")]
        SistemaBandaEdoOaxaca.ServiceReference1.GetEstacionesResponse GetEstaciones(SistemaBandaEdoOaxaca.ServiceReference1.GetEstacionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEstaciones", ReplyAction="*")]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.ServiceReference1.GetEstacionesResponse> GetEstacionesAsync(SistemaBandaEdoOaxaca.ServiceReference1.GetEstacionesRequest request);
        
        // CODEGEN: Generating message contract since element name estacion from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEstadisticos", ReplyAction="*")]
        SistemaBandaEdoOaxaca.ServiceReference1.GetEstadisticosResponse GetEstadisticos(SistemaBandaEdoOaxaca.ServiceReference1.GetEstadisticosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEstadisticos", ReplyAction="*")]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.ServiceReference1.GetEstadisticosResponse> GetEstadisticosAsync(SistemaBandaEdoOaxaca.ServiceReference1.GetEstadisticosRequest request);
        
        // CODEGEN: Generating message contract since element name nombre from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEstacionesPorNombre", ReplyAction="*")]
        SistemaBandaEdoOaxaca.ServiceReference1.GetEstacionesPorNombreResponse GetEstacionesPorNombre(SistemaBandaEdoOaxaca.ServiceReference1.GetEstacionesPorNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEstacionesPorNombre", ReplyAction="*")]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.ServiceReference1.GetEstacionesPorNombreResponse> GetEstacionesPorNombreAsync(SistemaBandaEdoOaxaca.ServiceReference1.GetEstacionesPorNombreRequest request);
        
        // CODEGEN: Generating message contract since element name GetPronosticosResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPronosticos", ReplyAction="*")]
        SistemaBandaEdoOaxaca.ServiceReference1.GetPronosticosResponse GetPronosticos(SistemaBandaEdoOaxaca.ServiceReference1.GetPronosticosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPronosticos", ReplyAction="*")]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.ServiceReference1.GetPronosticosResponse> GetPronosticosAsync(SistemaBandaEdoOaxaca.ServiceReference1.GetPronosticosRequest request);
        
        // CODEGEN: Generating message contract since element name idEdo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReporteEst", ReplyAction="*")]
        SistemaBandaEdoOaxaca.ServiceReference1.ReporteEstResponse ReporteEst(SistemaBandaEdoOaxaca.ServiceReference1.ReporteEstRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReporteEst", ReplyAction="*")]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.ServiceReference1.ReporteEstResponse> ReporteEstAsync(SistemaBandaEdoOaxaca.ServiceReference1.ReporteEstRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnviarReporteEst", ReplyAction="*")]
        SistemaBandaEdoOaxaca.ServiceReference1.EnviarReporteEstResponse EnviarReporteEst(SistemaBandaEdoOaxaca.ServiceReference1.EnviarReporteEstRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnviarReporteEst", ReplyAction="*")]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.ServiceReference1.EnviarReporteEstResponse> EnviarReporteEstAsync(SistemaBandaEdoOaxaca.ServiceReference1.EnviarReporteEstRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(SistemaBandaEdoOaxaca.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(SistemaBandaEdoOaxaca.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Mario", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.ServiceReference1.MarioRequestBody Body;
        
        public MarioRequest() {
        }
        
        public MarioRequest(SistemaBandaEdoOaxaca.ServiceReference1.MarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int opc;
        
        public MarioRequestBody() {
        }
        
        public MarioRequestBody(int opc) {
            this.opc = opc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.ServiceReference1.MarioResponseBody Body;
        
        public MarioResponse() {
        }
        
        public MarioResponse(SistemaBandaEdoOaxaca.ServiceReference1.MarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MarioResult;
        
        public MarioResponseBody() {
        }
        
        public MarioResponseBody(string MarioResult) {
            this.MarioResult = MarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class THIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="THI", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.ServiceReference1.THIRequestBody Body;
        
        public THIRequest() {
        }
        
        public THIRequest(SistemaBandaEdoOaxaca.ServiceReference1.THIRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class THIRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numero;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string edo;
        
        public THIRequestBody() {
        }
        
        public THIRequestBody(string numero, string edo) {
            this.numero = numero;
            this.edo = edo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class THIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="THIResponse", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.ServiceReference1.THIResponseBody Body;
        
        public THIResponse() {
        }
        
        public THIResponse(SistemaBandaEdoOaxaca.ServiceReference1.THIResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class THIResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string THIResult;
        
        public THIResponseBody() {
        }
        
        public THIResponseBody(string THIResult) {
            this.THIResult = THIResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EstacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Estacion", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.ServiceReference1.EstacionRequestBody Body;
        
        public EstacionRequest() {
        }
        
        public EstacionRequest(SistemaBandaEdoOaxaca.ServiceReference1.EstacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EstacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numero;
        
        public EstacionRequestBody() {
        }
        
        public EstacionRequestBody(string numero) {
            this.numero = numero;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EstacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EstacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.ServiceReference1.EstacionResponseBody Body;
        
        public EstacionResponse() {
        }
        
        public EstacionResponse(SistemaBandaEdoOaxaca.ServiceReference1.EstacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EstacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EstacionResult;
        
        public EstacionResponseBody() {
        }
        
        public EstacionResponseBody(string EstacionResult) {
            this.EstacionResult = EstacionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EstacionDatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EstacionDatos", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.ServiceReference1.EstacionDatosRequestBody Body;
        
        public EstacionDatosRequest() {
        }
        
        public EstacionDatosRequest(SistemaBandaEdoOaxaca.ServiceReference1.EstacionDatosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EstacionDatosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numero;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string edo;
        
        public EstacionDatosRequestBody() {
        }
        
        public EstacionDatosRequestBody(string numero, string edo) {
            this.numero = numero;
            this.edo = edo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EstacionDatosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EstacionDatosResponse", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.ServiceReference1.EstacionDatosResponseBody Body;
        
        public EstacionDatosResponse() {
        }
        
        public EstacionDatosResponse(SistemaBandaEdoOaxaca.ServiceReference1.EstacionDatosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EstacionDatosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EstacionDatosResult;
        
        public EstacionDatosResponseBody() {
        }
        
        public EstacionDatosResponseBody(string EstacionDatosResult) {
            this.EstacionDatosResult = EstacionDatosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataStationTemtHumrRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataStationTemtHumr", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.ServiceReference1.GetDataStationTemtHumrRequestBody Body;
        
        public GetDataStationTemtHumrRequest() {
        }
        
        public GetDataStationTemtHumrRequest(SistemaBandaEdoOaxaca.ServiceReference1.GetDataStationTemtHumrRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataStationTemtHumrRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int numero;
        
        public GetDataStationTemtHumrRequestBody() {
        }
        
        public GetDataStationTemtHumrRequestBody(int numero) {
            this.numero = numero;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataStationTemtHumrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataStationTemtHumrResponse", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.ServiceReference1.GetDataStationTemtHumrResponseBody Body;
        
        public GetDataStationTemtHumrResponse() {
        }
        
        public GetDataStationTemtHumrResponse(SistemaBandaEdoOaxaca.ServiceReference1.GetDataStationTemtHumrResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataStationTemtHumrResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDataStationTemtHumrResult;
        
        public GetDataStationTemtHumrResponseBody() {
        }
        
        public GetDataStationTemtHumrResponseBody(string GetDataStationTemtHumrResult) {
            this.GetDataStationTemtHumrResult = GetDataStationTemtHumrResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GPSEstacionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GPSEstaciones", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.ServiceReference1.GPSEstacionesRequestBody Body;
        
        public GPSEstacionesRequest() {
        }
        
        public GPSEstacionesRequest(SistemaBandaEdoOaxaca.ServiceReference1.GPSEstacionesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GPSEstacionesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double latitud;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double longi;
        
        public GPSEstacionesRequestBody() {
        }
        
        public GPSEstacionesRequestBody(double latitud, double longi) {
            this.latitud = latitud;
            this.longi = longi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GPSEstacionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GPSEstacionesResponse", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.ServiceReference1.GPSEstacionesResponseBody Body;
        
        public GPSEstacionesResponse() {
        }
        
        public GPSEstacionesResponse(SistemaBandaEdoOaxaca.ServiceReference1.GPSEstacionesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GPSEstacionesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GPSEstacionesResult;
        
        public GPSEstacionesResponseBody() {
        }
        
        public GPSEstacionesResponseBody(string GPSEstacionesResult) {
            this.GPSEstacionesResult = GPSEstacionesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEstacionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEstaciones", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.ServiceReference1.GetEstacionesRequestBody Body;
        
        public GetEstacionesRequest() {
        }
        
        public GetEstacionesRequest(SistemaBandaEdoOaxaca.ServiceReference1.GetEstacionesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEstacionesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string edo;
        
        public GetEstacionesRequestBody() {
        }
        
        public GetEstacionesRequestBody(string edo) {
            this.edo = edo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEstacionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEstacionesResponse", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.ServiceReference1.GetEstacionesResponseBody Body;
        
        public GetEstacionesResponse() {
        }
        
        public GetEstacionesResponse(SistemaBandaEdoOaxaca.ServiceReference1.GetEstacionesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEstacionesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetEstacionesResult;
        
        public GetEstacionesResponseBody() {
        }
        
        public GetEstacionesResponseBody(string GetEstacionesResult) {
            this.GetEstacionesResult = GetEstacionesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEstadisticosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEstadisticos", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.ServiceReference1.GetEstadisticosRequestBody Body;
        
        public GetEstadisticosRequest() {
        }
        
        public GetEstadisticosRequest(SistemaBandaEdoOaxaca.ServiceReference1.GetEstadisticosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEstadisticosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string estacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string edo;
        
        public GetEstadisticosRequestBody() {
        }
        
        public GetEstadisticosRequestBody(string estacion, string edo) {
            this.estacion = estacion;
            this.edo = edo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEstadisticosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEstadisticosResponse", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.ServiceReference1.GetEstadisticosResponseBody Body;
        
        public GetEstadisticosResponse() {
        }
        
        public GetEstadisticosResponse(SistemaBandaEdoOaxaca.ServiceReference1.GetEstadisticosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEstadisticosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetEstadisticosResult;
        
        public GetEstadisticosResponseBody() {
        }
        
        public GetEstadisticosResponseBody(string GetEstadisticosResult) {
            this.GetEstadisticosResult = GetEstadisticosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEstacionesPorNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEstacionesPorNombre", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.ServiceReference1.GetEstacionesPorNombreRequestBody Body;
        
        public GetEstacionesPorNombreRequest() {
        }
        
        public GetEstacionesPorNombreRequest(SistemaBandaEdoOaxaca.ServiceReference1.GetEstacionesPorNombreRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEstacionesPorNombreRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        public GetEstacionesPorNombreRequestBody() {
        }
        
        public GetEstacionesPorNombreRequestBody(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEstacionesPorNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEstacionesPorNombreResponse", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.ServiceReference1.GetEstacionesPorNombreResponseBody Body;
        
        public GetEstacionesPorNombreResponse() {
        }
        
        public GetEstacionesPorNombreResponse(SistemaBandaEdoOaxaca.ServiceReference1.GetEstacionesPorNombreResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEstacionesPorNombreResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetEstacionesPorNombreResult;
        
        public GetEstacionesPorNombreResponseBody() {
        }
        
        public GetEstacionesPorNombreResponseBody(string GetEstacionesPorNombreResult) {
            this.GetEstacionesPorNombreResult = GetEstacionesPorNombreResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPronosticosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPronosticos", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.ServiceReference1.GetPronosticosRequestBody Body;
        
        public GetPronosticosRequest() {
        }
        
        public GetPronosticosRequest(SistemaBandaEdoOaxaca.ServiceReference1.GetPronosticosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPronosticosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int numero;
        
        public GetPronosticosRequestBody() {
        }
        
        public GetPronosticosRequestBody(int numero) {
            this.numero = numero;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPronosticosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPronosticosResponse", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.ServiceReference1.GetPronosticosResponseBody Body;
        
        public GetPronosticosResponse() {
        }
        
        public GetPronosticosResponse(SistemaBandaEdoOaxaca.ServiceReference1.GetPronosticosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPronosticosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetPronosticosResult;
        
        public GetPronosticosResponseBody() {
        }
        
        public GetPronosticosResponseBody(string GetPronosticosResult) {
            this.GetPronosticosResult = GetPronosticosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReporteEstRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReporteEst", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.ServiceReference1.ReporteEstRequestBody Body;
        
        public ReporteEstRequest() {
        }
        
        public ReporteEstRequest(SistemaBandaEdoOaxaca.ServiceReference1.ReporteEstRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReporteEstRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idEdo;
        
        public ReporteEstRequestBody() {
        }
        
        public ReporteEstRequestBody(string idEdo) {
            this.idEdo = idEdo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReporteEstResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReporteEstResponse", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.ServiceReference1.ReporteEstResponseBody Body;
        
        public ReporteEstResponse() {
        }
        
        public ReporteEstResponse(SistemaBandaEdoOaxaca.ServiceReference1.ReporteEstResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReporteEstResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReporteEstResult;
        
        public ReporteEstResponseBody() {
        }
        
        public ReporteEstResponseBody(string ReporteEstResult) {
            this.ReporteEstResult = ReporteEstResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviarReporteEstRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviarReporteEst", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.ServiceReference1.EnviarReporteEstRequestBody Body;
        
        public EnviarReporteEstRequest() {
        }
        
        public EnviarReporteEstRequest(SistemaBandaEdoOaxaca.ServiceReference1.EnviarReporteEstRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnviarReporteEstRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idEdo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string email;
        
        public EnviarReporteEstRequestBody() {
        }
        
        public EnviarReporteEstRequestBody(int idEdo, string email) {
            this.idEdo = idEdo;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviarReporteEstResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviarReporteEstResponse", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.ServiceReference1.EnviarReporteEstResponseBody Body;
        
        public EnviarReporteEstResponse() {
        }
        
        public EnviarReporteEstResponse(SistemaBandaEdoOaxaca.ServiceReference1.EnviarReporteEstResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnviarReporteEstResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EnviarReporteEstResult;
        
        public EnviarReporteEstResponseBody() {
        }
        
        public EnviarReporteEstResponseBody(string EnviarReporteEstResult) {
            this.EnviarReporteEstResult = EnviarReporteEstResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap>, SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaBandaEdoOaxaca.ServiceReference1.HelloWorldResponse SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap.HelloWorld(SistemaBandaEdoOaxaca.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            SistemaBandaEdoOaxaca.ServiceReference1.HelloWorldRequest inValue = new SistemaBandaEdoOaxaca.ServiceReference1.HelloWorldRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.ServiceReference1.HelloWorldRequestBody();
            SistemaBandaEdoOaxaca.ServiceReference1.HelloWorldResponse retVal = ((SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.ServiceReference1.HelloWorldResponse> SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap.HelloWorldAsync(SistemaBandaEdoOaxaca.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            SistemaBandaEdoOaxaca.ServiceReference1.HelloWorldRequest inValue = new SistemaBandaEdoOaxaca.ServiceReference1.HelloWorldRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.ServiceReference1.HelloWorldRequestBody();
            return ((SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaBandaEdoOaxaca.ServiceReference1.MarioResponse SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap.Mario(SistemaBandaEdoOaxaca.ServiceReference1.MarioRequest request) {
            return base.Channel.Mario(request);
        }
        
        public string Mario(int opc) {
            SistemaBandaEdoOaxaca.ServiceReference1.MarioRequest inValue = new SistemaBandaEdoOaxaca.ServiceReference1.MarioRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.ServiceReference1.MarioRequestBody();
            inValue.Body.opc = opc;
            SistemaBandaEdoOaxaca.ServiceReference1.MarioResponse retVal = ((SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap)(this)).Mario(inValue);
            return retVal.Body.MarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.ServiceReference1.MarioResponse> SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap.MarioAsync(SistemaBandaEdoOaxaca.ServiceReference1.MarioRequest request) {
            return base.Channel.MarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.ServiceReference1.MarioResponse> MarioAsync(int opc) {
            SistemaBandaEdoOaxaca.ServiceReference1.MarioRequest inValue = new SistemaBandaEdoOaxaca.ServiceReference1.MarioRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.ServiceReference1.MarioRequestBody();
            inValue.Body.opc = opc;
            return ((SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap)(this)).MarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaBandaEdoOaxaca.ServiceReference1.THIResponse SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap.THI(SistemaBandaEdoOaxaca.ServiceReference1.THIRequest request) {
            return base.Channel.THI(request);
        }
        
        public string THI(string numero, string edo) {
            SistemaBandaEdoOaxaca.ServiceReference1.THIRequest inValue = new SistemaBandaEdoOaxaca.ServiceReference1.THIRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.ServiceReference1.THIRequestBody();
            inValue.Body.numero = numero;
            inValue.Body.edo = edo;
            SistemaBandaEdoOaxaca.ServiceReference1.THIResponse retVal = ((SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap)(this)).THI(inValue);
            return retVal.Body.THIResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.ServiceReference1.THIResponse> SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap.THIAsync(SistemaBandaEdoOaxaca.ServiceReference1.THIRequest request) {
            return base.Channel.THIAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.ServiceReference1.THIResponse> THIAsync(string numero, string edo) {
            SistemaBandaEdoOaxaca.ServiceReference1.THIRequest inValue = new SistemaBandaEdoOaxaca.ServiceReference1.THIRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.ServiceReference1.THIRequestBody();
            inValue.Body.numero = numero;
            inValue.Body.edo = edo;
            return ((SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap)(this)).THIAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaBandaEdoOaxaca.ServiceReference1.EstacionResponse SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap.Estacion(SistemaBandaEdoOaxaca.ServiceReference1.EstacionRequest request) {
            return base.Channel.Estacion(request);
        }
        
        public string Estacion(string numero) {
            SistemaBandaEdoOaxaca.ServiceReference1.EstacionRequest inValue = new SistemaBandaEdoOaxaca.ServiceReference1.EstacionRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.ServiceReference1.EstacionRequestBody();
            inValue.Body.numero = numero;
            SistemaBandaEdoOaxaca.ServiceReference1.EstacionResponse retVal = ((SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap)(this)).Estacion(inValue);
            return retVal.Body.EstacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.ServiceReference1.EstacionResponse> SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap.EstacionAsync(SistemaBandaEdoOaxaca.ServiceReference1.EstacionRequest request) {
            return base.Channel.EstacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.ServiceReference1.EstacionResponse> EstacionAsync(string numero) {
            SistemaBandaEdoOaxaca.ServiceReference1.EstacionRequest inValue = new SistemaBandaEdoOaxaca.ServiceReference1.EstacionRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.ServiceReference1.EstacionRequestBody();
            inValue.Body.numero = numero;
            return ((SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap)(this)).EstacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaBandaEdoOaxaca.ServiceReference1.EstacionDatosResponse SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap.EstacionDatos(SistemaBandaEdoOaxaca.ServiceReference1.EstacionDatosRequest request) {
            return base.Channel.EstacionDatos(request);
        }
        
        public string EstacionDatos(string numero, string edo) {
            SistemaBandaEdoOaxaca.ServiceReference1.EstacionDatosRequest inValue = new SistemaBandaEdoOaxaca.ServiceReference1.EstacionDatosRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.ServiceReference1.EstacionDatosRequestBody();
            inValue.Body.numero = numero;
            inValue.Body.edo = edo;
            SistemaBandaEdoOaxaca.ServiceReference1.EstacionDatosResponse retVal = ((SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap)(this)).EstacionDatos(inValue);
            return retVal.Body.EstacionDatosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.ServiceReference1.EstacionDatosResponse> SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap.EstacionDatosAsync(SistemaBandaEdoOaxaca.ServiceReference1.EstacionDatosRequest request) {
            return base.Channel.EstacionDatosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.ServiceReference1.EstacionDatosResponse> EstacionDatosAsync(string numero, string edo) {
            SistemaBandaEdoOaxaca.ServiceReference1.EstacionDatosRequest inValue = new SistemaBandaEdoOaxaca.ServiceReference1.EstacionDatosRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.ServiceReference1.EstacionDatosRequestBody();
            inValue.Body.numero = numero;
            inValue.Body.edo = edo;
            return ((SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap)(this)).EstacionDatosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaBandaEdoOaxaca.ServiceReference1.GetDataStationTemtHumrResponse SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap.GetDataStationTemtHumr(SistemaBandaEdoOaxaca.ServiceReference1.GetDataStationTemtHumrRequest request) {
            return base.Channel.GetDataStationTemtHumr(request);
        }
        
        public string GetDataStationTemtHumr(int numero) {
            SistemaBandaEdoOaxaca.ServiceReference1.GetDataStationTemtHumrRequest inValue = new SistemaBandaEdoOaxaca.ServiceReference1.GetDataStationTemtHumrRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.ServiceReference1.GetDataStationTemtHumrRequestBody();
            inValue.Body.numero = numero;
            SistemaBandaEdoOaxaca.ServiceReference1.GetDataStationTemtHumrResponse retVal = ((SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap)(this)).GetDataStationTemtHumr(inValue);
            return retVal.Body.GetDataStationTemtHumrResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.ServiceReference1.GetDataStationTemtHumrResponse> SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap.GetDataStationTemtHumrAsync(SistemaBandaEdoOaxaca.ServiceReference1.GetDataStationTemtHumrRequest request) {
            return base.Channel.GetDataStationTemtHumrAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.ServiceReference1.GetDataStationTemtHumrResponse> GetDataStationTemtHumrAsync(int numero) {
            SistemaBandaEdoOaxaca.ServiceReference1.GetDataStationTemtHumrRequest inValue = new SistemaBandaEdoOaxaca.ServiceReference1.GetDataStationTemtHumrRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.ServiceReference1.GetDataStationTemtHumrRequestBody();
            inValue.Body.numero = numero;
            return ((SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap)(this)).GetDataStationTemtHumrAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaBandaEdoOaxaca.ServiceReference1.GPSEstacionesResponse SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap.GPSEstaciones(SistemaBandaEdoOaxaca.ServiceReference1.GPSEstacionesRequest request) {
            return base.Channel.GPSEstaciones(request);
        }
        
        public string GPSEstaciones(double latitud, double longi) {
            SistemaBandaEdoOaxaca.ServiceReference1.GPSEstacionesRequest inValue = new SistemaBandaEdoOaxaca.ServiceReference1.GPSEstacionesRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.ServiceReference1.GPSEstacionesRequestBody();
            inValue.Body.latitud = latitud;
            inValue.Body.longi = longi;
            SistemaBandaEdoOaxaca.ServiceReference1.GPSEstacionesResponse retVal = ((SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap)(this)).GPSEstaciones(inValue);
            return retVal.Body.GPSEstacionesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.ServiceReference1.GPSEstacionesResponse> SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap.GPSEstacionesAsync(SistemaBandaEdoOaxaca.ServiceReference1.GPSEstacionesRequest request) {
            return base.Channel.GPSEstacionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.ServiceReference1.GPSEstacionesResponse> GPSEstacionesAsync(double latitud, double longi) {
            SistemaBandaEdoOaxaca.ServiceReference1.GPSEstacionesRequest inValue = new SistemaBandaEdoOaxaca.ServiceReference1.GPSEstacionesRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.ServiceReference1.GPSEstacionesRequestBody();
            inValue.Body.latitud = latitud;
            inValue.Body.longi = longi;
            return ((SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap)(this)).GPSEstacionesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaBandaEdoOaxaca.ServiceReference1.GetEstacionesResponse SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap.GetEstaciones(SistemaBandaEdoOaxaca.ServiceReference1.GetEstacionesRequest request) {
            return base.Channel.GetEstaciones(request);
        }
        
        public string GetEstaciones(string edo) {
            SistemaBandaEdoOaxaca.ServiceReference1.GetEstacionesRequest inValue = new SistemaBandaEdoOaxaca.ServiceReference1.GetEstacionesRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.ServiceReference1.GetEstacionesRequestBody();
            inValue.Body.edo = edo;
            SistemaBandaEdoOaxaca.ServiceReference1.GetEstacionesResponse retVal = ((SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap)(this)).GetEstaciones(inValue);
            return retVal.Body.GetEstacionesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.ServiceReference1.GetEstacionesResponse> SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap.GetEstacionesAsync(SistemaBandaEdoOaxaca.ServiceReference1.GetEstacionesRequest request) {
            return base.Channel.GetEstacionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.ServiceReference1.GetEstacionesResponse> GetEstacionesAsync(string edo) {
            SistemaBandaEdoOaxaca.ServiceReference1.GetEstacionesRequest inValue = new SistemaBandaEdoOaxaca.ServiceReference1.GetEstacionesRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.ServiceReference1.GetEstacionesRequestBody();
            inValue.Body.edo = edo;
            return ((SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap)(this)).GetEstacionesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaBandaEdoOaxaca.ServiceReference1.GetEstadisticosResponse SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap.GetEstadisticos(SistemaBandaEdoOaxaca.ServiceReference1.GetEstadisticosRequest request) {
            return base.Channel.GetEstadisticos(request);
        }
        
        public string GetEstadisticos(string estacion, string edo) {
            SistemaBandaEdoOaxaca.ServiceReference1.GetEstadisticosRequest inValue = new SistemaBandaEdoOaxaca.ServiceReference1.GetEstadisticosRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.ServiceReference1.GetEstadisticosRequestBody();
            inValue.Body.estacion = estacion;
            inValue.Body.edo = edo;
            SistemaBandaEdoOaxaca.ServiceReference1.GetEstadisticosResponse retVal = ((SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap)(this)).GetEstadisticos(inValue);
            return retVal.Body.GetEstadisticosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.ServiceReference1.GetEstadisticosResponse> SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap.GetEstadisticosAsync(SistemaBandaEdoOaxaca.ServiceReference1.GetEstadisticosRequest request) {
            return base.Channel.GetEstadisticosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.ServiceReference1.GetEstadisticosResponse> GetEstadisticosAsync(string estacion, string edo) {
            SistemaBandaEdoOaxaca.ServiceReference1.GetEstadisticosRequest inValue = new SistemaBandaEdoOaxaca.ServiceReference1.GetEstadisticosRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.ServiceReference1.GetEstadisticosRequestBody();
            inValue.Body.estacion = estacion;
            inValue.Body.edo = edo;
            return ((SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap)(this)).GetEstadisticosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaBandaEdoOaxaca.ServiceReference1.GetEstacionesPorNombreResponse SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap.GetEstacionesPorNombre(SistemaBandaEdoOaxaca.ServiceReference1.GetEstacionesPorNombreRequest request) {
            return base.Channel.GetEstacionesPorNombre(request);
        }
        
        public string GetEstacionesPorNombre(string nombre) {
            SistemaBandaEdoOaxaca.ServiceReference1.GetEstacionesPorNombreRequest inValue = new SistemaBandaEdoOaxaca.ServiceReference1.GetEstacionesPorNombreRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.ServiceReference1.GetEstacionesPorNombreRequestBody();
            inValue.Body.nombre = nombre;
            SistemaBandaEdoOaxaca.ServiceReference1.GetEstacionesPorNombreResponse retVal = ((SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap)(this)).GetEstacionesPorNombre(inValue);
            return retVal.Body.GetEstacionesPorNombreResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.ServiceReference1.GetEstacionesPorNombreResponse> SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap.GetEstacionesPorNombreAsync(SistemaBandaEdoOaxaca.ServiceReference1.GetEstacionesPorNombreRequest request) {
            return base.Channel.GetEstacionesPorNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.ServiceReference1.GetEstacionesPorNombreResponse> GetEstacionesPorNombreAsync(string nombre) {
            SistemaBandaEdoOaxaca.ServiceReference1.GetEstacionesPorNombreRequest inValue = new SistemaBandaEdoOaxaca.ServiceReference1.GetEstacionesPorNombreRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.ServiceReference1.GetEstacionesPorNombreRequestBody();
            inValue.Body.nombre = nombre;
            return ((SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap)(this)).GetEstacionesPorNombreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaBandaEdoOaxaca.ServiceReference1.GetPronosticosResponse SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap.GetPronosticos(SistemaBandaEdoOaxaca.ServiceReference1.GetPronosticosRequest request) {
            return base.Channel.GetPronosticos(request);
        }
        
        public string GetPronosticos(int numero) {
            SistemaBandaEdoOaxaca.ServiceReference1.GetPronosticosRequest inValue = new SistemaBandaEdoOaxaca.ServiceReference1.GetPronosticosRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.ServiceReference1.GetPronosticosRequestBody();
            inValue.Body.numero = numero;
            SistemaBandaEdoOaxaca.ServiceReference1.GetPronosticosResponse retVal = ((SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap)(this)).GetPronosticos(inValue);
            return retVal.Body.GetPronosticosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.ServiceReference1.GetPronosticosResponse> SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap.GetPronosticosAsync(SistemaBandaEdoOaxaca.ServiceReference1.GetPronosticosRequest request) {
            return base.Channel.GetPronosticosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.ServiceReference1.GetPronosticosResponse> GetPronosticosAsync(int numero) {
            SistemaBandaEdoOaxaca.ServiceReference1.GetPronosticosRequest inValue = new SistemaBandaEdoOaxaca.ServiceReference1.GetPronosticosRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.ServiceReference1.GetPronosticosRequestBody();
            inValue.Body.numero = numero;
            return ((SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap)(this)).GetPronosticosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaBandaEdoOaxaca.ServiceReference1.ReporteEstResponse SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap.ReporteEst(SistemaBandaEdoOaxaca.ServiceReference1.ReporteEstRequest request) {
            return base.Channel.ReporteEst(request);
        }
        
        public string ReporteEst(string idEdo) {
            SistemaBandaEdoOaxaca.ServiceReference1.ReporteEstRequest inValue = new SistemaBandaEdoOaxaca.ServiceReference1.ReporteEstRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.ServiceReference1.ReporteEstRequestBody();
            inValue.Body.idEdo = idEdo;
            SistemaBandaEdoOaxaca.ServiceReference1.ReporteEstResponse retVal = ((SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap)(this)).ReporteEst(inValue);
            return retVal.Body.ReporteEstResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.ServiceReference1.ReporteEstResponse> SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap.ReporteEstAsync(SistemaBandaEdoOaxaca.ServiceReference1.ReporteEstRequest request) {
            return base.Channel.ReporteEstAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.ServiceReference1.ReporteEstResponse> ReporteEstAsync(string idEdo) {
            SistemaBandaEdoOaxaca.ServiceReference1.ReporteEstRequest inValue = new SistemaBandaEdoOaxaca.ServiceReference1.ReporteEstRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.ServiceReference1.ReporteEstRequestBody();
            inValue.Body.idEdo = idEdo;
            return ((SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap)(this)).ReporteEstAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaBandaEdoOaxaca.ServiceReference1.EnviarReporteEstResponse SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap.EnviarReporteEst(SistemaBandaEdoOaxaca.ServiceReference1.EnviarReporteEstRequest request) {
            return base.Channel.EnviarReporteEst(request);
        }
        
        public string EnviarReporteEst(int idEdo, string email) {
            SistemaBandaEdoOaxaca.ServiceReference1.EnviarReporteEstRequest inValue = new SistemaBandaEdoOaxaca.ServiceReference1.EnviarReporteEstRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.ServiceReference1.EnviarReporteEstRequestBody();
            inValue.Body.idEdo = idEdo;
            inValue.Body.email = email;
            SistemaBandaEdoOaxaca.ServiceReference1.EnviarReporteEstResponse retVal = ((SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap)(this)).EnviarReporteEst(inValue);
            return retVal.Body.EnviarReporteEstResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.ServiceReference1.EnviarReporteEstResponse> SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap.EnviarReporteEstAsync(SistemaBandaEdoOaxaca.ServiceReference1.EnviarReporteEstRequest request) {
            return base.Channel.EnviarReporteEstAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.ServiceReference1.EnviarReporteEstResponse> EnviarReporteEstAsync(int idEdo, string email) {
            SistemaBandaEdoOaxaca.ServiceReference1.EnviarReporteEstRequest inValue = new SistemaBandaEdoOaxaca.ServiceReference1.EnviarReporteEstRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.ServiceReference1.EnviarReporteEstRequestBody();
            inValue.Body.idEdo = idEdo;
            inValue.Body.email = email;
            return ((SistemaBandaEdoOaxaca.ServiceReference1.WebServiceSoap)(this)).EnviarReporteEstAsync(inValue);
        }
    }
}
