//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaBandaEdoOaxaca.Clima {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Clima.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        SistemaBandaEdoOaxaca.Clima.HelloWorldResponse HelloWorld(SistemaBandaEdoOaxaca.Clima.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.Clima.HelloWorldResponse> HelloWorldAsync(SistemaBandaEdoOaxaca.Clima.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name MarioResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Mario", ReplyAction="*")]
        SistemaBandaEdoOaxaca.Clima.MarioResponse Mario(SistemaBandaEdoOaxaca.Clima.MarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Mario", ReplyAction="*")]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.Clima.MarioResponse> MarioAsync(SistemaBandaEdoOaxaca.Clima.MarioRequest request);
        
        // CODEGEN: Generating message contract since element name numero from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/THI", ReplyAction="*")]
        SistemaBandaEdoOaxaca.Clima.THIResponse THI(SistemaBandaEdoOaxaca.Clima.THIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/THI", ReplyAction="*")]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.Clima.THIResponse> THIAsync(SistemaBandaEdoOaxaca.Clima.THIRequest request);
        
        // CODEGEN: Generating message contract since element name numero from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Estacion", ReplyAction="*")]
        SistemaBandaEdoOaxaca.Clima.EstacionResponse Estacion(SistemaBandaEdoOaxaca.Clima.EstacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Estacion", ReplyAction="*")]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.Clima.EstacionResponse> EstacionAsync(SistemaBandaEdoOaxaca.Clima.EstacionRequest request);
        
        // CODEGEN: Generating message contract since element name numero from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EstacionDatos", ReplyAction="*")]
        SistemaBandaEdoOaxaca.Clima.EstacionDatosResponse EstacionDatos(SistemaBandaEdoOaxaca.Clima.EstacionDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EstacionDatos", ReplyAction="*")]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.Clima.EstacionDatosResponse> EstacionDatosAsync(SistemaBandaEdoOaxaca.Clima.EstacionDatosRequest request);
        
        // CODEGEN: Generating message contract since element name GetDataStationTemtHumrResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataStationTemtHumr", ReplyAction="*")]
        SistemaBandaEdoOaxaca.Clima.GetDataStationTemtHumrResponse GetDataStationTemtHumr(SistemaBandaEdoOaxaca.Clima.GetDataStationTemtHumrRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataStationTemtHumr", ReplyAction="*")]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.Clima.GetDataStationTemtHumrResponse> GetDataStationTemtHumrAsync(SistemaBandaEdoOaxaca.Clima.GetDataStationTemtHumrRequest request);
        
        // CODEGEN: Generating message contract since element name GPSEstacionesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GPSEstaciones", ReplyAction="*")]
        SistemaBandaEdoOaxaca.Clima.GPSEstacionesResponse GPSEstaciones(SistemaBandaEdoOaxaca.Clima.GPSEstacionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GPSEstaciones", ReplyAction="*")]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.Clima.GPSEstacionesResponse> GPSEstacionesAsync(SistemaBandaEdoOaxaca.Clima.GPSEstacionesRequest request);
        
        // CODEGEN: Generating message contract since element name edo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEstaciones", ReplyAction="*")]
        SistemaBandaEdoOaxaca.Clima.GetEstacionesResponse GetEstaciones(SistemaBandaEdoOaxaca.Clima.GetEstacionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEstaciones", ReplyAction="*")]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.Clima.GetEstacionesResponse> GetEstacionesAsync(SistemaBandaEdoOaxaca.Clima.GetEstacionesRequest request);
        
        // CODEGEN: Generating message contract since element name estacion from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEstadisticos", ReplyAction="*")]
        SistemaBandaEdoOaxaca.Clima.GetEstadisticosResponse GetEstadisticos(SistemaBandaEdoOaxaca.Clima.GetEstadisticosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEstadisticos", ReplyAction="*")]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.Clima.GetEstadisticosResponse> GetEstadisticosAsync(SistemaBandaEdoOaxaca.Clima.GetEstadisticosRequest request);
        
        // CODEGEN: Generating message contract since element name nombre from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEstacionesPorNombre", ReplyAction="*")]
        SistemaBandaEdoOaxaca.Clima.GetEstacionesPorNombreResponse GetEstacionesPorNombre(SistemaBandaEdoOaxaca.Clima.GetEstacionesPorNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEstacionesPorNombre", ReplyAction="*")]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.Clima.GetEstacionesPorNombreResponse> GetEstacionesPorNombreAsync(SistemaBandaEdoOaxaca.Clima.GetEstacionesPorNombreRequest request);
        
        // CODEGEN: Generating message contract since element name GetPronosticosResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPronosticos", ReplyAction="*")]
        SistemaBandaEdoOaxaca.Clima.GetPronosticosResponse GetPronosticos(SistemaBandaEdoOaxaca.Clima.GetPronosticosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPronosticos", ReplyAction="*")]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.Clima.GetPronosticosResponse> GetPronosticosAsync(SistemaBandaEdoOaxaca.Clima.GetPronosticosRequest request);
        
        // CODEGEN: Generating message contract since element name idEdo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReporteEst", ReplyAction="*")]
        SistemaBandaEdoOaxaca.Clima.ReporteEstResponse ReporteEst(SistemaBandaEdoOaxaca.Clima.ReporteEstRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReporteEst", ReplyAction="*")]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.Clima.ReporteEstResponse> ReporteEstAsync(SistemaBandaEdoOaxaca.Clima.ReporteEstRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnviarReporteEst", ReplyAction="*")]
        SistemaBandaEdoOaxaca.Clima.EnviarReporteEstResponse EnviarReporteEst(SistemaBandaEdoOaxaca.Clima.EnviarReporteEstRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnviarReporteEst", ReplyAction="*")]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.Clima.EnviarReporteEstResponse> EnviarReporteEstAsync(SistemaBandaEdoOaxaca.Clima.EnviarReporteEstRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.Clima.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(SistemaBandaEdoOaxaca.Clima.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.Clima.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(SistemaBandaEdoOaxaca.Clima.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Mario", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.Clima.MarioRequestBody Body;
        
        public MarioRequest() {
        }
        
        public MarioRequest(SistemaBandaEdoOaxaca.Clima.MarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int opc;
        
        public MarioRequestBody() {
        }
        
        public MarioRequestBody(int opc) {
            this.opc = opc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.Clima.MarioResponseBody Body;
        
        public MarioResponse() {
        }
        
        public MarioResponse(SistemaBandaEdoOaxaca.Clima.MarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MarioResult;
        
        public MarioResponseBody() {
        }
        
        public MarioResponseBody(string MarioResult) {
            this.MarioResult = MarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class THIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="THI", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.Clima.THIRequestBody Body;
        
        public THIRequest() {
        }
        
        public THIRequest(SistemaBandaEdoOaxaca.Clima.THIRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class THIRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numero;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string edo;
        
        public THIRequestBody() {
        }
        
        public THIRequestBody(string numero, string edo) {
            this.numero = numero;
            this.edo = edo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class THIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="THIResponse", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.Clima.THIResponseBody Body;
        
        public THIResponse() {
        }
        
        public THIResponse(SistemaBandaEdoOaxaca.Clima.THIResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class THIResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string THIResult;
        
        public THIResponseBody() {
        }
        
        public THIResponseBody(string THIResult) {
            this.THIResult = THIResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EstacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Estacion", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.Clima.EstacionRequestBody Body;
        
        public EstacionRequest() {
        }
        
        public EstacionRequest(SistemaBandaEdoOaxaca.Clima.EstacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EstacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numero;
        
        public EstacionRequestBody() {
        }
        
        public EstacionRequestBody(string numero) {
            this.numero = numero;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EstacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EstacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.Clima.EstacionResponseBody Body;
        
        public EstacionResponse() {
        }
        
        public EstacionResponse(SistemaBandaEdoOaxaca.Clima.EstacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EstacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EstacionResult;
        
        public EstacionResponseBody() {
        }
        
        public EstacionResponseBody(string EstacionResult) {
            this.EstacionResult = EstacionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EstacionDatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EstacionDatos", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.Clima.EstacionDatosRequestBody Body;
        
        public EstacionDatosRequest() {
        }
        
        public EstacionDatosRequest(SistemaBandaEdoOaxaca.Clima.EstacionDatosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EstacionDatosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numero;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string edo;
        
        public EstacionDatosRequestBody() {
        }
        
        public EstacionDatosRequestBody(string numero, string edo) {
            this.numero = numero;
            this.edo = edo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EstacionDatosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EstacionDatosResponse", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.Clima.EstacionDatosResponseBody Body;
        
        public EstacionDatosResponse() {
        }
        
        public EstacionDatosResponse(SistemaBandaEdoOaxaca.Clima.EstacionDatosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EstacionDatosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EstacionDatosResult;
        
        public EstacionDatosResponseBody() {
        }
        
        public EstacionDatosResponseBody(string EstacionDatosResult) {
            this.EstacionDatosResult = EstacionDatosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataStationTemtHumrRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataStationTemtHumr", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.Clima.GetDataStationTemtHumrRequestBody Body;
        
        public GetDataStationTemtHumrRequest() {
        }
        
        public GetDataStationTemtHumrRequest(SistemaBandaEdoOaxaca.Clima.GetDataStationTemtHumrRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataStationTemtHumrRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int numero;
        
        public GetDataStationTemtHumrRequestBody() {
        }
        
        public GetDataStationTemtHumrRequestBody(int numero) {
            this.numero = numero;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataStationTemtHumrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataStationTemtHumrResponse", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.Clima.GetDataStationTemtHumrResponseBody Body;
        
        public GetDataStationTemtHumrResponse() {
        }
        
        public GetDataStationTemtHumrResponse(SistemaBandaEdoOaxaca.Clima.GetDataStationTemtHumrResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataStationTemtHumrResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDataStationTemtHumrResult;
        
        public GetDataStationTemtHumrResponseBody() {
        }
        
        public GetDataStationTemtHumrResponseBody(string GetDataStationTemtHumrResult) {
            this.GetDataStationTemtHumrResult = GetDataStationTemtHumrResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GPSEstacionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GPSEstaciones", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.Clima.GPSEstacionesRequestBody Body;
        
        public GPSEstacionesRequest() {
        }
        
        public GPSEstacionesRequest(SistemaBandaEdoOaxaca.Clima.GPSEstacionesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GPSEstacionesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double latitud;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double longi;
        
        public GPSEstacionesRequestBody() {
        }
        
        public GPSEstacionesRequestBody(double latitud, double longi) {
            this.latitud = latitud;
            this.longi = longi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GPSEstacionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GPSEstacionesResponse", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.Clima.GPSEstacionesResponseBody Body;
        
        public GPSEstacionesResponse() {
        }
        
        public GPSEstacionesResponse(SistemaBandaEdoOaxaca.Clima.GPSEstacionesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GPSEstacionesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GPSEstacionesResult;
        
        public GPSEstacionesResponseBody() {
        }
        
        public GPSEstacionesResponseBody(string GPSEstacionesResult) {
            this.GPSEstacionesResult = GPSEstacionesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEstacionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEstaciones", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.Clima.GetEstacionesRequestBody Body;
        
        public GetEstacionesRequest() {
        }
        
        public GetEstacionesRequest(SistemaBandaEdoOaxaca.Clima.GetEstacionesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEstacionesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string edo;
        
        public GetEstacionesRequestBody() {
        }
        
        public GetEstacionesRequestBody(string edo) {
            this.edo = edo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEstacionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEstacionesResponse", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.Clima.GetEstacionesResponseBody Body;
        
        public GetEstacionesResponse() {
        }
        
        public GetEstacionesResponse(SistemaBandaEdoOaxaca.Clima.GetEstacionesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEstacionesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetEstacionesResult;
        
        public GetEstacionesResponseBody() {
        }
        
        public GetEstacionesResponseBody(string GetEstacionesResult) {
            this.GetEstacionesResult = GetEstacionesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEstadisticosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEstadisticos", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.Clima.GetEstadisticosRequestBody Body;
        
        public GetEstadisticosRequest() {
        }
        
        public GetEstadisticosRequest(SistemaBandaEdoOaxaca.Clima.GetEstadisticosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEstadisticosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string estacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string edo;
        
        public GetEstadisticosRequestBody() {
        }
        
        public GetEstadisticosRequestBody(string estacion, string edo) {
            this.estacion = estacion;
            this.edo = edo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEstadisticosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEstadisticosResponse", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.Clima.GetEstadisticosResponseBody Body;
        
        public GetEstadisticosResponse() {
        }
        
        public GetEstadisticosResponse(SistemaBandaEdoOaxaca.Clima.GetEstadisticosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEstadisticosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetEstadisticosResult;
        
        public GetEstadisticosResponseBody() {
        }
        
        public GetEstadisticosResponseBody(string GetEstadisticosResult) {
            this.GetEstadisticosResult = GetEstadisticosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEstacionesPorNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEstacionesPorNombre", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.Clima.GetEstacionesPorNombreRequestBody Body;
        
        public GetEstacionesPorNombreRequest() {
        }
        
        public GetEstacionesPorNombreRequest(SistemaBandaEdoOaxaca.Clima.GetEstacionesPorNombreRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEstacionesPorNombreRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        public GetEstacionesPorNombreRequestBody() {
        }
        
        public GetEstacionesPorNombreRequestBody(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEstacionesPorNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEstacionesPorNombreResponse", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.Clima.GetEstacionesPorNombreResponseBody Body;
        
        public GetEstacionesPorNombreResponse() {
        }
        
        public GetEstacionesPorNombreResponse(SistemaBandaEdoOaxaca.Clima.GetEstacionesPorNombreResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEstacionesPorNombreResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetEstacionesPorNombreResult;
        
        public GetEstacionesPorNombreResponseBody() {
        }
        
        public GetEstacionesPorNombreResponseBody(string GetEstacionesPorNombreResult) {
            this.GetEstacionesPorNombreResult = GetEstacionesPorNombreResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPronosticosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPronosticos", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.Clima.GetPronosticosRequestBody Body;
        
        public GetPronosticosRequest() {
        }
        
        public GetPronosticosRequest(SistemaBandaEdoOaxaca.Clima.GetPronosticosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPronosticosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int numero;
        
        public GetPronosticosRequestBody() {
        }
        
        public GetPronosticosRequestBody(int numero) {
            this.numero = numero;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPronosticosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPronosticosResponse", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.Clima.GetPronosticosResponseBody Body;
        
        public GetPronosticosResponse() {
        }
        
        public GetPronosticosResponse(SistemaBandaEdoOaxaca.Clima.GetPronosticosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPronosticosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetPronosticosResult;
        
        public GetPronosticosResponseBody() {
        }
        
        public GetPronosticosResponseBody(string GetPronosticosResult) {
            this.GetPronosticosResult = GetPronosticosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReporteEstRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReporteEst", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.Clima.ReporteEstRequestBody Body;
        
        public ReporteEstRequest() {
        }
        
        public ReporteEstRequest(SistemaBandaEdoOaxaca.Clima.ReporteEstRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReporteEstRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idEdo;
        
        public ReporteEstRequestBody() {
        }
        
        public ReporteEstRequestBody(string idEdo) {
            this.idEdo = idEdo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReporteEstResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReporteEstResponse", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.Clima.ReporteEstResponseBody Body;
        
        public ReporteEstResponse() {
        }
        
        public ReporteEstResponse(SistemaBandaEdoOaxaca.Clima.ReporteEstResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReporteEstResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReporteEstResult;
        
        public ReporteEstResponseBody() {
        }
        
        public ReporteEstResponseBody(string ReporteEstResult) {
            this.ReporteEstResult = ReporteEstResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviarReporteEstRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviarReporteEst", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.Clima.EnviarReporteEstRequestBody Body;
        
        public EnviarReporteEstRequest() {
        }
        
        public EnviarReporteEstRequest(SistemaBandaEdoOaxaca.Clima.EnviarReporteEstRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnviarReporteEstRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idEdo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string email;
        
        public EnviarReporteEstRequestBody() {
        }
        
        public EnviarReporteEstRequestBody(int idEdo, string email) {
            this.idEdo = idEdo;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviarReporteEstResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviarReporteEstResponse", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBandaEdoOaxaca.Clima.EnviarReporteEstResponseBody Body;
        
        public EnviarReporteEstResponse() {
        }
        
        public EnviarReporteEstResponse(SistemaBandaEdoOaxaca.Clima.EnviarReporteEstResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnviarReporteEstResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EnviarReporteEstResult;
        
        public EnviarReporteEstResponseBody() {
        }
        
        public EnviarReporteEstResponseBody(string EnviarReporteEstResult) {
            this.EnviarReporteEstResult = EnviarReporteEstResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : SistemaBandaEdoOaxaca.Clima.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<SistemaBandaEdoOaxaca.Clima.WebServiceSoap>, SistemaBandaEdoOaxaca.Clima.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaBandaEdoOaxaca.Clima.HelloWorldResponse SistemaBandaEdoOaxaca.Clima.WebServiceSoap.HelloWorld(SistemaBandaEdoOaxaca.Clima.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            SistemaBandaEdoOaxaca.Clima.HelloWorldRequest inValue = new SistemaBandaEdoOaxaca.Clima.HelloWorldRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.Clima.HelloWorldRequestBody();
            SistemaBandaEdoOaxaca.Clima.HelloWorldResponse retVal = ((SistemaBandaEdoOaxaca.Clima.WebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.Clima.HelloWorldResponse> SistemaBandaEdoOaxaca.Clima.WebServiceSoap.HelloWorldAsync(SistemaBandaEdoOaxaca.Clima.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.Clima.HelloWorldResponse> HelloWorldAsync() {
            SistemaBandaEdoOaxaca.Clima.HelloWorldRequest inValue = new SistemaBandaEdoOaxaca.Clima.HelloWorldRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.Clima.HelloWorldRequestBody();
            return ((SistemaBandaEdoOaxaca.Clima.WebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaBandaEdoOaxaca.Clima.MarioResponse SistemaBandaEdoOaxaca.Clima.WebServiceSoap.Mario(SistemaBandaEdoOaxaca.Clima.MarioRequest request) {
            return base.Channel.Mario(request);
        }
        
        public string Mario(int opc) {
            SistemaBandaEdoOaxaca.Clima.MarioRequest inValue = new SistemaBandaEdoOaxaca.Clima.MarioRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.Clima.MarioRequestBody();
            inValue.Body.opc = opc;
            SistemaBandaEdoOaxaca.Clima.MarioResponse retVal = ((SistemaBandaEdoOaxaca.Clima.WebServiceSoap)(this)).Mario(inValue);
            return retVal.Body.MarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.Clima.MarioResponse> SistemaBandaEdoOaxaca.Clima.WebServiceSoap.MarioAsync(SistemaBandaEdoOaxaca.Clima.MarioRequest request) {
            return base.Channel.MarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.Clima.MarioResponse> MarioAsync(int opc) {
            SistemaBandaEdoOaxaca.Clima.MarioRequest inValue = new SistemaBandaEdoOaxaca.Clima.MarioRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.Clima.MarioRequestBody();
            inValue.Body.opc = opc;
            return ((SistemaBandaEdoOaxaca.Clima.WebServiceSoap)(this)).MarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaBandaEdoOaxaca.Clima.THIResponse SistemaBandaEdoOaxaca.Clima.WebServiceSoap.THI(SistemaBandaEdoOaxaca.Clima.THIRequest request) {
            return base.Channel.THI(request);
        }
        
        public string THI(string numero, string edo) {
            SistemaBandaEdoOaxaca.Clima.THIRequest inValue = new SistemaBandaEdoOaxaca.Clima.THIRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.Clima.THIRequestBody();
            inValue.Body.numero = numero;
            inValue.Body.edo = edo;
            SistemaBandaEdoOaxaca.Clima.THIResponse retVal = ((SistemaBandaEdoOaxaca.Clima.WebServiceSoap)(this)).THI(inValue);
            return retVal.Body.THIResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.Clima.THIResponse> SistemaBandaEdoOaxaca.Clima.WebServiceSoap.THIAsync(SistemaBandaEdoOaxaca.Clima.THIRequest request) {
            return base.Channel.THIAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.Clima.THIResponse> THIAsync(string numero, string edo) {
            SistemaBandaEdoOaxaca.Clima.THIRequest inValue = new SistemaBandaEdoOaxaca.Clima.THIRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.Clima.THIRequestBody();
            inValue.Body.numero = numero;
            inValue.Body.edo = edo;
            return ((SistemaBandaEdoOaxaca.Clima.WebServiceSoap)(this)).THIAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaBandaEdoOaxaca.Clima.EstacionResponse SistemaBandaEdoOaxaca.Clima.WebServiceSoap.Estacion(SistemaBandaEdoOaxaca.Clima.EstacionRequest request) {
            return base.Channel.Estacion(request);
        }
        
        public string Estacion(string numero) {
            SistemaBandaEdoOaxaca.Clima.EstacionRequest inValue = new SistemaBandaEdoOaxaca.Clima.EstacionRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.Clima.EstacionRequestBody();
            inValue.Body.numero = numero;
            SistemaBandaEdoOaxaca.Clima.EstacionResponse retVal = ((SistemaBandaEdoOaxaca.Clima.WebServiceSoap)(this)).Estacion(inValue);
            return retVal.Body.EstacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.Clima.EstacionResponse> SistemaBandaEdoOaxaca.Clima.WebServiceSoap.EstacionAsync(SistemaBandaEdoOaxaca.Clima.EstacionRequest request) {
            return base.Channel.EstacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.Clima.EstacionResponse> EstacionAsync(string numero) {
            SistemaBandaEdoOaxaca.Clima.EstacionRequest inValue = new SistemaBandaEdoOaxaca.Clima.EstacionRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.Clima.EstacionRequestBody();
            inValue.Body.numero = numero;
            return ((SistemaBandaEdoOaxaca.Clima.WebServiceSoap)(this)).EstacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaBandaEdoOaxaca.Clima.EstacionDatosResponse SistemaBandaEdoOaxaca.Clima.WebServiceSoap.EstacionDatos(SistemaBandaEdoOaxaca.Clima.EstacionDatosRequest request) {
            return base.Channel.EstacionDatos(request);
        }
        
        public string EstacionDatos(string numero, string edo) {
            SistemaBandaEdoOaxaca.Clima.EstacionDatosRequest inValue = new SistemaBandaEdoOaxaca.Clima.EstacionDatosRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.Clima.EstacionDatosRequestBody();
            inValue.Body.numero = numero;
            inValue.Body.edo = edo;
            SistemaBandaEdoOaxaca.Clima.EstacionDatosResponse retVal = ((SistemaBandaEdoOaxaca.Clima.WebServiceSoap)(this)).EstacionDatos(inValue);
            return retVal.Body.EstacionDatosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.Clima.EstacionDatosResponse> SistemaBandaEdoOaxaca.Clima.WebServiceSoap.EstacionDatosAsync(SistemaBandaEdoOaxaca.Clima.EstacionDatosRequest request) {
            return base.Channel.EstacionDatosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.Clima.EstacionDatosResponse> EstacionDatosAsync(string numero, string edo) {
            SistemaBandaEdoOaxaca.Clima.EstacionDatosRequest inValue = new SistemaBandaEdoOaxaca.Clima.EstacionDatosRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.Clima.EstacionDatosRequestBody();
            inValue.Body.numero = numero;
            inValue.Body.edo = edo;
            return ((SistemaBandaEdoOaxaca.Clima.WebServiceSoap)(this)).EstacionDatosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaBandaEdoOaxaca.Clima.GetDataStationTemtHumrResponse SistemaBandaEdoOaxaca.Clima.WebServiceSoap.GetDataStationTemtHumr(SistemaBandaEdoOaxaca.Clima.GetDataStationTemtHumrRequest request) {
            return base.Channel.GetDataStationTemtHumr(request);
        }
        
        public string GetDataStationTemtHumr(int numero) {
            SistemaBandaEdoOaxaca.Clima.GetDataStationTemtHumrRequest inValue = new SistemaBandaEdoOaxaca.Clima.GetDataStationTemtHumrRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.Clima.GetDataStationTemtHumrRequestBody();
            inValue.Body.numero = numero;
            SistemaBandaEdoOaxaca.Clima.GetDataStationTemtHumrResponse retVal = ((SistemaBandaEdoOaxaca.Clima.WebServiceSoap)(this)).GetDataStationTemtHumr(inValue);
            return retVal.Body.GetDataStationTemtHumrResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.Clima.GetDataStationTemtHumrResponse> SistemaBandaEdoOaxaca.Clima.WebServiceSoap.GetDataStationTemtHumrAsync(SistemaBandaEdoOaxaca.Clima.GetDataStationTemtHumrRequest request) {
            return base.Channel.GetDataStationTemtHumrAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.Clima.GetDataStationTemtHumrResponse> GetDataStationTemtHumrAsync(int numero) {
            SistemaBandaEdoOaxaca.Clima.GetDataStationTemtHumrRequest inValue = new SistemaBandaEdoOaxaca.Clima.GetDataStationTemtHumrRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.Clima.GetDataStationTemtHumrRequestBody();
            inValue.Body.numero = numero;
            return ((SistemaBandaEdoOaxaca.Clima.WebServiceSoap)(this)).GetDataStationTemtHumrAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaBandaEdoOaxaca.Clima.GPSEstacionesResponse SistemaBandaEdoOaxaca.Clima.WebServiceSoap.GPSEstaciones(SistemaBandaEdoOaxaca.Clima.GPSEstacionesRequest request) {
            return base.Channel.GPSEstaciones(request);
        }
        
        public string GPSEstaciones(double latitud, double longi) {
            SistemaBandaEdoOaxaca.Clima.GPSEstacionesRequest inValue = new SistemaBandaEdoOaxaca.Clima.GPSEstacionesRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.Clima.GPSEstacionesRequestBody();
            inValue.Body.latitud = latitud;
            inValue.Body.longi = longi;
            SistemaBandaEdoOaxaca.Clima.GPSEstacionesResponse retVal = ((SistemaBandaEdoOaxaca.Clima.WebServiceSoap)(this)).GPSEstaciones(inValue);
            return retVal.Body.GPSEstacionesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.Clima.GPSEstacionesResponse> SistemaBandaEdoOaxaca.Clima.WebServiceSoap.GPSEstacionesAsync(SistemaBandaEdoOaxaca.Clima.GPSEstacionesRequest request) {
            return base.Channel.GPSEstacionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.Clima.GPSEstacionesResponse> GPSEstacionesAsync(double latitud, double longi) {
            SistemaBandaEdoOaxaca.Clima.GPSEstacionesRequest inValue = new SistemaBandaEdoOaxaca.Clima.GPSEstacionesRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.Clima.GPSEstacionesRequestBody();
            inValue.Body.latitud = latitud;
            inValue.Body.longi = longi;
            return ((SistemaBandaEdoOaxaca.Clima.WebServiceSoap)(this)).GPSEstacionesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaBandaEdoOaxaca.Clima.GetEstacionesResponse SistemaBandaEdoOaxaca.Clima.WebServiceSoap.GetEstaciones(SistemaBandaEdoOaxaca.Clima.GetEstacionesRequest request) {
            return base.Channel.GetEstaciones(request);
        }
        
        public string GetEstaciones(string edo) {
            SistemaBandaEdoOaxaca.Clima.GetEstacionesRequest inValue = new SistemaBandaEdoOaxaca.Clima.GetEstacionesRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.Clima.GetEstacionesRequestBody();
            inValue.Body.edo = edo;
            SistemaBandaEdoOaxaca.Clima.GetEstacionesResponse retVal = ((SistemaBandaEdoOaxaca.Clima.WebServiceSoap)(this)).GetEstaciones(inValue);
            return retVal.Body.GetEstacionesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.Clima.GetEstacionesResponse> SistemaBandaEdoOaxaca.Clima.WebServiceSoap.GetEstacionesAsync(SistemaBandaEdoOaxaca.Clima.GetEstacionesRequest request) {
            return base.Channel.GetEstacionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.Clima.GetEstacionesResponse> GetEstacionesAsync(string edo) {
            SistemaBandaEdoOaxaca.Clima.GetEstacionesRequest inValue = new SistemaBandaEdoOaxaca.Clima.GetEstacionesRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.Clima.GetEstacionesRequestBody();
            inValue.Body.edo = edo;
            return ((SistemaBandaEdoOaxaca.Clima.WebServiceSoap)(this)).GetEstacionesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaBandaEdoOaxaca.Clima.GetEstadisticosResponse SistemaBandaEdoOaxaca.Clima.WebServiceSoap.GetEstadisticos(SistemaBandaEdoOaxaca.Clima.GetEstadisticosRequest request) {
            return base.Channel.GetEstadisticos(request);
        }
        
        public string GetEstadisticos(string estacion, string edo) {
            SistemaBandaEdoOaxaca.Clima.GetEstadisticosRequest inValue = new SistemaBandaEdoOaxaca.Clima.GetEstadisticosRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.Clima.GetEstadisticosRequestBody();
            inValue.Body.estacion = estacion;
            inValue.Body.edo = edo;
            SistemaBandaEdoOaxaca.Clima.GetEstadisticosResponse retVal = ((SistemaBandaEdoOaxaca.Clima.WebServiceSoap)(this)).GetEstadisticos(inValue);
            return retVal.Body.GetEstadisticosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.Clima.GetEstadisticosResponse> SistemaBandaEdoOaxaca.Clima.WebServiceSoap.GetEstadisticosAsync(SistemaBandaEdoOaxaca.Clima.GetEstadisticosRequest request) {
            return base.Channel.GetEstadisticosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.Clima.GetEstadisticosResponse> GetEstadisticosAsync(string estacion, string edo) {
            SistemaBandaEdoOaxaca.Clima.GetEstadisticosRequest inValue = new SistemaBandaEdoOaxaca.Clima.GetEstadisticosRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.Clima.GetEstadisticosRequestBody();
            inValue.Body.estacion = estacion;
            inValue.Body.edo = edo;
            return ((SistemaBandaEdoOaxaca.Clima.WebServiceSoap)(this)).GetEstadisticosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaBandaEdoOaxaca.Clima.GetEstacionesPorNombreResponse SistemaBandaEdoOaxaca.Clima.WebServiceSoap.GetEstacionesPorNombre(SistemaBandaEdoOaxaca.Clima.GetEstacionesPorNombreRequest request) {
            return base.Channel.GetEstacionesPorNombre(request);
        }
        
        public string GetEstacionesPorNombre(string nombre) {
            SistemaBandaEdoOaxaca.Clima.GetEstacionesPorNombreRequest inValue = new SistemaBandaEdoOaxaca.Clima.GetEstacionesPorNombreRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.Clima.GetEstacionesPorNombreRequestBody();
            inValue.Body.nombre = nombre;
            SistemaBandaEdoOaxaca.Clima.GetEstacionesPorNombreResponse retVal = ((SistemaBandaEdoOaxaca.Clima.WebServiceSoap)(this)).GetEstacionesPorNombre(inValue);
            return retVal.Body.GetEstacionesPorNombreResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.Clima.GetEstacionesPorNombreResponse> SistemaBandaEdoOaxaca.Clima.WebServiceSoap.GetEstacionesPorNombreAsync(SistemaBandaEdoOaxaca.Clima.GetEstacionesPorNombreRequest request) {
            return base.Channel.GetEstacionesPorNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.Clima.GetEstacionesPorNombreResponse> GetEstacionesPorNombreAsync(string nombre) {
            SistemaBandaEdoOaxaca.Clima.GetEstacionesPorNombreRequest inValue = new SistemaBandaEdoOaxaca.Clima.GetEstacionesPorNombreRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.Clima.GetEstacionesPorNombreRequestBody();
            inValue.Body.nombre = nombre;
            return ((SistemaBandaEdoOaxaca.Clima.WebServiceSoap)(this)).GetEstacionesPorNombreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaBandaEdoOaxaca.Clima.GetPronosticosResponse SistemaBandaEdoOaxaca.Clima.WebServiceSoap.GetPronosticos(SistemaBandaEdoOaxaca.Clima.GetPronosticosRequest request) {
            return base.Channel.GetPronosticos(request);
        }
        
        public string GetPronosticos(int numero) {
            SistemaBandaEdoOaxaca.Clima.GetPronosticosRequest inValue = new SistemaBandaEdoOaxaca.Clima.GetPronosticosRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.Clima.GetPronosticosRequestBody();
            inValue.Body.numero = numero;
            SistemaBandaEdoOaxaca.Clima.GetPronosticosResponse retVal = ((SistemaBandaEdoOaxaca.Clima.WebServiceSoap)(this)).GetPronosticos(inValue);
            return retVal.Body.GetPronosticosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.Clima.GetPronosticosResponse> SistemaBandaEdoOaxaca.Clima.WebServiceSoap.GetPronosticosAsync(SistemaBandaEdoOaxaca.Clima.GetPronosticosRequest request) {
            return base.Channel.GetPronosticosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.Clima.GetPronosticosResponse> GetPronosticosAsync(int numero) {
            SistemaBandaEdoOaxaca.Clima.GetPronosticosRequest inValue = new SistemaBandaEdoOaxaca.Clima.GetPronosticosRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.Clima.GetPronosticosRequestBody();
            inValue.Body.numero = numero;
            return ((SistemaBandaEdoOaxaca.Clima.WebServiceSoap)(this)).GetPronosticosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaBandaEdoOaxaca.Clima.ReporteEstResponse SistemaBandaEdoOaxaca.Clima.WebServiceSoap.ReporteEst(SistemaBandaEdoOaxaca.Clima.ReporteEstRequest request) {
            return base.Channel.ReporteEst(request);
        }
        
        public string ReporteEst(string idEdo) {
            SistemaBandaEdoOaxaca.Clima.ReporteEstRequest inValue = new SistemaBandaEdoOaxaca.Clima.ReporteEstRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.Clima.ReporteEstRequestBody();
            inValue.Body.idEdo = idEdo;
            SistemaBandaEdoOaxaca.Clima.ReporteEstResponse retVal = ((SistemaBandaEdoOaxaca.Clima.WebServiceSoap)(this)).ReporteEst(inValue);
            return retVal.Body.ReporteEstResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.Clima.ReporteEstResponse> SistemaBandaEdoOaxaca.Clima.WebServiceSoap.ReporteEstAsync(SistemaBandaEdoOaxaca.Clima.ReporteEstRequest request) {
            return base.Channel.ReporteEstAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.Clima.ReporteEstResponse> ReporteEstAsync(string idEdo) {
            SistemaBandaEdoOaxaca.Clima.ReporteEstRequest inValue = new SistemaBandaEdoOaxaca.Clima.ReporteEstRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.Clima.ReporteEstRequestBody();
            inValue.Body.idEdo = idEdo;
            return ((SistemaBandaEdoOaxaca.Clima.WebServiceSoap)(this)).ReporteEstAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaBandaEdoOaxaca.Clima.EnviarReporteEstResponse SistemaBandaEdoOaxaca.Clima.WebServiceSoap.EnviarReporteEst(SistemaBandaEdoOaxaca.Clima.EnviarReporteEstRequest request) {
            return base.Channel.EnviarReporteEst(request);
        }
        
        public string EnviarReporteEst(int idEdo, string email) {
            SistemaBandaEdoOaxaca.Clima.EnviarReporteEstRequest inValue = new SistemaBandaEdoOaxaca.Clima.EnviarReporteEstRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.Clima.EnviarReporteEstRequestBody();
            inValue.Body.idEdo = idEdo;
            inValue.Body.email = email;
            SistemaBandaEdoOaxaca.Clima.EnviarReporteEstResponse retVal = ((SistemaBandaEdoOaxaca.Clima.WebServiceSoap)(this)).EnviarReporteEst(inValue);
            return retVal.Body.EnviarReporteEstResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.Clima.EnviarReporteEstResponse> SistemaBandaEdoOaxaca.Clima.WebServiceSoap.EnviarReporteEstAsync(SistemaBandaEdoOaxaca.Clima.EnviarReporteEstRequest request) {
            return base.Channel.EnviarReporteEstAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.Clima.EnviarReporteEstResponse> EnviarReporteEstAsync(int idEdo, string email) {
            SistemaBandaEdoOaxaca.Clima.EnviarReporteEstRequest inValue = new SistemaBandaEdoOaxaca.Clima.EnviarReporteEstRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.Clima.EnviarReporteEstRequestBody();
            inValue.Body.idEdo = idEdo;
            inValue.Body.email = email;
            return ((SistemaBandaEdoOaxaca.Clima.WebServiceSoap)(this)).EnviarReporteEstAsync(inValue);
        }
    }
}
