//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaBandaEdoOaxaca.WebDemo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bandadeledooaxaca.com/", ConfigurationName="WebDemo.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://bandadeledooaxaca.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://bandadeledooaxaca.com/HelloWorld", ReplyAction="*")]
        SistemaBandaEdoOaxaca.WebDemo.HelloWorldResponse HelloWorld(SistemaBandaEdoOaxaca.WebDemo.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bandadeledooaxaca.com/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.WebDemo.HelloWorldResponse> HelloWorldAsync(SistemaBandaEdoOaxaca.WebDemo.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bandadeledooaxaca.com/SumaDeDosNumeros", ReplyAction="*")]
        int SumaDeDosNumeros(int num, int num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bandadeledooaxaca.com/SumaDeDosNumeros", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SumaDeDosNumerosAsync(int num, int num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bandadeledooaxaca.com/Mensaje", ReplyAction="*")]
        void Mensaje();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bandadeledooaxaca.com/Mensaje", ReplyAction="*")]
        System.Threading.Tasks.Task MensajeAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://bandadeledooaxaca.com/", Order=0)]
        public SistemaBandaEdoOaxaca.WebDemo.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(SistemaBandaEdoOaxaca.WebDemo.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://bandadeledooaxaca.com/", Order=0)]
        public SistemaBandaEdoOaxaca.WebDemo.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(SistemaBandaEdoOaxaca.WebDemo.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bandadeledooaxaca.com/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : SistemaBandaEdoOaxaca.WebDemo.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<SistemaBandaEdoOaxaca.WebDemo.WebService1Soap>, SistemaBandaEdoOaxaca.WebDemo.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaBandaEdoOaxaca.WebDemo.HelloWorldResponse SistemaBandaEdoOaxaca.WebDemo.WebService1Soap.HelloWorld(SistemaBandaEdoOaxaca.WebDemo.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            SistemaBandaEdoOaxaca.WebDemo.HelloWorldRequest inValue = new SistemaBandaEdoOaxaca.WebDemo.HelloWorldRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.WebDemo.HelloWorldRequestBody();
            SistemaBandaEdoOaxaca.WebDemo.HelloWorldResponse retVal = ((SistemaBandaEdoOaxaca.WebDemo.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.WebDemo.HelloWorldResponse> SistemaBandaEdoOaxaca.WebDemo.WebService1Soap.HelloWorldAsync(SistemaBandaEdoOaxaca.WebDemo.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaBandaEdoOaxaca.WebDemo.HelloWorldResponse> HelloWorldAsync() {
            SistemaBandaEdoOaxaca.WebDemo.HelloWorldRequest inValue = new SistemaBandaEdoOaxaca.WebDemo.HelloWorldRequest();
            inValue.Body = new SistemaBandaEdoOaxaca.WebDemo.HelloWorldRequestBody();
            return ((SistemaBandaEdoOaxaca.WebDemo.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        public int SumaDeDosNumeros(int num, int num2) {
            return base.Channel.SumaDeDosNumeros(num, num2);
        }
        
        public System.Threading.Tasks.Task<int> SumaDeDosNumerosAsync(int num, int num2) {
            return base.Channel.SumaDeDosNumerosAsync(num, num2);
        }
        
        public void Mensaje() {
            base.Channel.Mensaje();
        }
        
        public System.Threading.Tasks.Task MensajeAsync() {
            return base.Channel.MensajeAsync();
        }
    }
}
