//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaBandaEdoOaxaca
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BandaDelEstadoEntities : DbContext
    {
        public BandaDelEstadoEntities()
            : base("name=BandaDelEstadoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cuenta> Cuenta { get; set; }
        public virtual DbSet<Direccion> Direccion { get; set; }
        public virtual DbSet<DonacionExterna> DonacionExterna { get; set; }
        public virtual DbSet<DonacionInterna> DonacionInterna { get; set; }
        public virtual DbSet<Donante> Donante { get; set; }
        public virtual DbSet<Estados> Estados { get; set; }
        public virtual DbSet<EventosProximos> EventosProximos { get; set; }
        public virtual DbSet<Genero> Genero { get; set; }
        public virtual DbSet<Instrumentos> Instrumentos { get; set; }
        public virtual DbSet<Musico> Musico { get; set; }
        public virtual DbSet<ObraMusical> ObraMusical { get; set; }
        public virtual DbSet<ObrasRecibidas> ObrasRecibidas { get; set; }
        public virtual DbSet<ProgramaDominical> ProgramaDominical { get; set; }
        public virtual DbSet<Solicitante> Solicitante { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<catalogocoord> catalogocoord { get; set; }
    }
}
