//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaBandaEdoOaxaca
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalogocoord
    {
        public string clavecct { get; set; }
        public string latitud2 { get; set; }
        public string longitud2 { get; set; }
        public string nombrect { get; set; }
        public string lada { get; set; }
        public string telefono1 { get; set; }
    }
}
