//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaBandaEdoOaxaca
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventosProximos
    {
        public string idEvento { get; set; }
        public string fecha { get; set; }
        public string lugar { get; set; }
        public string horaEmpiezo { get; set; }
        public string horaSalida { get; set; }
        public string Orden { get; set; }
    }
}
