//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaBandaEdoOaxaca
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Musico()
        {
            this.DonacionInterna = new HashSet<DonacionInterna>();
        }
    
        public string idMusico { get; set; }
        public string idCuenta { get; set; }
        public string idDireccion { get; set; }
        public string nombre { get; set; }
        public string apellidoPaterno { get; set; }
        public string apellidoMaterno { get; set; }
        public string telefono { get; set; }
        public string numEmpleado { get; set; }
        public string nivel { get; set; }
        public string nss { get; set; }
        public string gradoEstudios { get; set; }
        public string idInstrumento { get; set; }
        public string correo { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }
        public virtual Direccion Direccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonacionInterna> DonacionInterna { get; set; }
        public virtual Instrumentos Instrumentos { get; set; }
    }
}
