//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaBandaEdoOaxaca
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObraMusical
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ObraMusical()
        {
            this.DonacionExterna = new HashSet<DonacionExterna>();
            this.DonacionInterna = new HashSet<DonacionInterna>();
            this.ObrasRecibidas = new HashSet<ObrasRecibidas>();
            this.ProgramaDominical = new HashSet<ProgramaDominical>();
        }
    
        public string folio { get; set; }
        public string tituloObra { get; set; }
        public string autor { get; set; }
        public string anio { get; set; }
        public string region { get; set; }
        public string disponibilidad { get; set; }
        public string paginas { get; set; }
        public string numPartichelas { get; set; }
        public string estado { get; set; }
        public string fechaIngreso { get; set; }
        public string idGenero { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonacionExterna> DonacionExterna { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonacionInterna> DonacionInterna { get; set; }
        public virtual Genero Genero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObrasRecibidas> ObrasRecibidas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramaDominical> ProgramaDominical { get; set; }
    }
}
