//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaBandaEdoOaxaca
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramaDominical
    {
        public string idProgramaDominical { get; set; }
        public string folio { get; set; }
        public string fecha { get; set; }
        public string lugar { get; set; }
    
        public virtual ObraMusical ObraMusical { get; set; }
    }
}
